### PR TITLE
Beta candidate

### PR DESCRIPTION
**Pull request by Sesivany**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
The `finish-args-unnecessary-xdg-config-access` error seems to be caused by one of these filesystem permissions:
```
            "--filesystem=xdg-config/gnupg:rw",
            "--filesystem=xdg-config/pki:rw",
```

**Comment by AsciiWolf** [comment]
bot, build

**Comment by Erick555** [comment]
Just change those two to:
```
            "--filesystem=~/.config/gnupg:rw",
            "--filesystem=~/.config/pki:rw",
```

and you should pass the linter without change in user workflow

**Comment by Erick555** [comment]
@Sesivany setting `GNUPGHOME` to `~/.config/gnupg` or making symlink is something that happens in the wild so I would recommend  following my advice in https://github.com/flathub/org.gnome.Evolution/pull/150#issuecomment-1874585304 rather than removing them completely.

**Pull request merged**
